return {
  ensure_installed = {
    "lua",
    "vim",
    "vimdoc",
    "typescript",
    "javascript",
    "html",
    "css",
    "bash",
    "scss",
    "toml",
    "tsx",
    "markdown",
    "sql",
    "go",
    "gomod",
    "gosum",
    "gowork",
    "proto",
    "vue",
    "c_sharp",
  },
  sync_install = false,
  auto_install = true,
  highlight = { enable = true, use_languagetree = true },
  indent = { enable = true },
}
